### ISSUE TITLE
Added data model hacking intro to Readme

### ISSUE THREAD

**Issue by benlachman** [AthensCommunitySoccer/MeteorBall#11]
e.g. add some bits about the data model and general pieces of the app.

**Comment by rickychilcott** [comment]
Working on documentation here: https://github.com/AthensCommunitySoccer/MeteorBall/wiki/Data-Model

**Comment by rickychilcott** [comment]
If we need to do a many-to-many relationship, we could review this: https://www.eventedmind.com/feed/meteor-how-to-publish-a-many-to-many-relationship

**Comment by rickychilcott** [comment]
![photo](https://cloud.githubusercontent.com/assets/445759/3085660/51b4fa4a-e517-11e3-9bdd-ddf10073dbbf.JPG)

White board from the night. Click on it so it isn't upside down... weird!

**Comment by benlachman** [comment]
Looks good. Thanks Ricky!
